---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 5m
  install:
    timeout: 5m
    remediation:
      retries: 1
  upgrade:
    timeout: 1m
    remediation:
      retries: 1
  chart:
    spec:
      chart: gitlab
      version: "9.6.1"
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
  values:
    global:
      hosts:
        domain: cipher.lab.local
        https: true # <- Enable HTTPS since Istio is handling TLS
        gitlab:
          name: gitlab.cipher.lab.local
        registry:
          name: registry.cipher.lab.local
        minio:
          name: minio.cipher.lab.local
      ingress:
        enabled: false
        configureCertmanager: false
    installCertmanager: false
    gitlab-runner:
      install: false
    certmanager-issuer:
      email: "noreply@example.com"

    gitlab:
      webservice:
        minReplicas: 1
        maxReplicas: 1
        replicaCount: 1
        service:
          type: ClusterIP
      url: "https://gitlab.cipher.lab.local" # <- Set external URL to HTTPS

    gitlab_rails: # <- Rails config for HTTPS generation
      gitlab_hostname: gitlab.cipher.lab.local
      gitlab_port: 443
      gitlab_https: true

    registry:
      hpa:
        minReplicas: 1
        maxReplicas: 1
      service:
        type: ClusterIP
    gitlab-shell:
      hpa:
        minReplicas: 1
        maxReplicas: 1
      service:
        type: ClusterIP
    minio:
      service:
        type: ClusterIP
