apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: homarr
  namespace: homarr
spec:
  hosts:
  - "dashboard.cipher.lab.local"
  gateways:
  - istio-system/wildcard-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: homarr
        port:
          number: 80
