apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: portainer
  namespace: portainer
spec:
  hosts:
  - "portainer.cipher.lab.local"
  gateways:
  - istio-system/wildcard-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: portainer
        port:
          number: 9000
