apiVersion: v1
kind: Namespace
metadata:
  name: gitlab
  labels:
    app.kubernetes.io/name: gitlab
    app.kubernetes.io/instance: gitlab
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 10m
  timeout: 10m
  install:
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
    remediation:
      retries: 3
  chart:
    spec:
      chart: gitlab
      version: "9.6.1"
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
  values:
    global:
      hosts:
        domain: cipher.lab.local
        https: false
        gitlab:
          name: gitlab.cipher.lab.local
        registry:
          name: registry.cipher.lab.local
        minio:
          name: minio.cipher.lab.local
      ingress:
        enabled: false
        configureCertmanager: false
      gitlab:
        url: "https://gitlab.cipher.lab.local"
    certmanager:
      enabled: false
    certmanager-issuer:
      email: "noreply@example.com"
    nginx-ingress:
      enabled: true
    gitlab:
      webservice:
        service:
          type: ClusterIP
    registry:
      service:
        type: ClusterIP
    gitlab-shell:
      service:
        type: ClusterIP
    minio:
      service:
        type: ClusterIP
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gitlab
  namespace: flux-system
spec:
  url: https://charts.gitlab.io/
  interval: 10m
