apiVersion: v1
kind: Namespace
metadata:
  name: gitlab
  labels:
    app.kubernetes.io/name: gitlab
    app.kubernetes.io/instance: gitlab
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab
  namespace: gitlab
spec:
  interval: 10m
  chart:
    spec:
      chart: gitlab
      version: "9.6.1"
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: flux-system
  values:
    global:
      edition: ce
      hosts:
        domain: gitlab.cipher.lab.local
      ingress:
        configureCertmanager: false
    gitlab:
      webservice:
        type: ClusterIP
        externalTrafficPolicy: Cluster
      unicorn:
        replicas: 1
      sidekiq:
        replicas: 1
    postgresql:
      postgresqlPassword: "gitlabpass"
      postgresqlDatabase: "gitlabhq_production"
    redis:
      password: "redispass"
    ingress:
      configureCertmanager: false
      annotations: {} # no SSL annotations
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gitlab
  namespace: flux-system
spec:
  url: https://charts.gitlab.io/
  interval: 10m
