apiVersion: v1
kind: Namespace
metadata:
  name: homarr
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homarr
  namespace: homarr
spec:
  interval: 5m
  releaseName: homarr
  chart:
    spec:
      chart: homarr
      sourceRef:
        kind: HelmRepository
        name: homarr
        namespace: flux-system
  values:
    rbac:
      enabled: true
    ingress:
      enabled: false
    # Additional values such as envSecrets, image tag, etc.
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: homarr
  namespace: flux-system
spec:
  interval: 10m
  url: "oci://ghcr.io/homarr-labs/charts/homarr" 

