apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 5m
  releaseName: kyverno
  chart:
    spec:
      chart: kyverno
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  values:
    replicaCount: 2
    podSecurityContext:
      runAsNonRoot: true
    rbac:
      create: true
    admissionController:
      replicas: 2
      service:
        type: ClusterIP
    metricsConfig:
      metricsPort: 8000
      metricsService:
        create: true
    backgroundController:
      enabled: true
--- 
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 10m
  url: https://kyverno.github.io/kyverno/

