apiVersion: v1
kind: Namespace
metadata:
  name: portainer
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
spec:
  interval: 5m
  releaseName: portainer
  chart:
    spec:
      chart: portainer
      sourceRef:
        kind: HelmRepository
        name: portainer
        namespace: flux-system
  install:
    createNamespace: true
  values:
    service:
      type: ClusterIP
    ingress:
      enabled: false
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: portainer
  namespace: flux-system
spec:
  interval: 10m
  url: https://portainer.github.io/k8s/
