apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus
  namespace: monitoring
spec:
  releaseName: kube-prometheus
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "56.6.2"  # You can update this
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 5m
  install:
    createNamespace: true
  values:
    grafana:
      adminPassword: admin123
      service:
        enabled: true
        type: ClusterIP
        port: 80
      ingress:
        enabled: false
    prometheus:
      service:
        type: ClusterIP
    alertmanager:
      service:
        type: ClusterIP
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  url: https://prometheus-community.github.io/helm-charts
  interval: 5m

