apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certificate
  namespace: flux-system
spec:
  interval: 5m
  path: ./certificate
  prune: true
  dependsOn:
    - name: helm-release
  sourceRef:
    kind: GitRepository
    name: flux-system

