apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: "internal-ca"
  secretName: internal-ca-secret
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer

