apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clusterissuer
  namespace: flux-system
spec:
  dependsOn:
    - name: helm-release
  interval: 5m
  path: ./cluster-issuer
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

