apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  interval: 5m
  releaseName: istio-ingressgateway
  chart:
    spec:
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  dependsOn:
    - name: istiod
      namespace: istio-system
  values:
    service:
      type: LoadBalancer
    labels:
      istio: ingressgateway
    revision: ""  # Only set if you're using revisioned installs

